name: IaC Security Scan - Checkov

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

permissions:
  contents: read

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: Checkov Scanning
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Run Checkov Scan
        id: checkov-scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: cloudformation/
          soft_fail: true
          quiet: true
          output_format: sarif
      - name: Results on GitHub Code Scanning Alerts
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
          category: Checkov
