name: IaC Security Scan - KICS

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: KICS Scanning
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Create Results Directory
        run: mkdir -p results
      - name: Run KICS Scan
        id: kics-scan
        uses: checkmarx/kics-action@v1.4
        with:
          path: .
          output_path: results/
          output_formats: "json,sarif"
          ignore_on_exit: all
      - name: Display KICS Results
        run: |
          cat results/results.json
      - name: Results on GitHub Code Scanning Alerts
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results/results.sarif
          category: KICS
