name: IaC Security Scan - Snyk Infrastructure as Code

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

permissions:
  contents: read
  
jobs:
  snyk-job:
    runs-on: ubuntu-latest
    name: Snyk Scanning
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Run Snyk Scan
        id: snyk-scan
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .
      - name: Results on GitHub Code Scanning Alerts
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'snyk.sarif'
          category: Snyk
