name: IaC Security Scan - Trivy

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: Trivy Scanning
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Run Trivy Scan
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          format: 'sarif'
          hide-progress: false
          output: 'results.sarif'
      - name: Results on GitHub Code Scanning Alerts
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
          category: Trivy
